
export const GET_ALL_ORDER_BY_USER_LOADING = "GET_ALL_ORDER_BY_USER_LOADING"
export const GET_ALL_ORDER_BY_USER_LOADED = "GET_ALL_ORDER_BY_USER_LOADED"
export const GET_ALL_ORDER_BY_USER_ERROR = "GET_ALL_ORDER_BY_USER_ERROR"
export const UPDATE_STATUS_ORDER_LOADING = "UPDATE_STATUS_ORDER_LOADING"
export const UPDATE_STATUS_ORDER_LOADED = "UPDATE_STATUS_ORDER_LOADED"
export const UPDATE_STATUS_ORDER_ERROR = "UPDATE_STATUS_ORDER_ERROR"
export const GET_ORDER_LOADING = "GET_ORDER_LOADING"
export const GET_ORDER_LOADED = "GET_ORDER_LOADED"
export const GET_ORDER_ERROR = "GET_ORDER_ERROR"




