export const GET_ALL_LOW_STOCK_LOADING = "GET_ALL_LOW_STOCK_LOADING"
export const GET_ALL_LOW_STOCK_LOADED = "GET_ALL_LOW_STOCK_LOADED"
export const GET_ALL_LOW_STOCK_ERROR = "GET_ALL_LOW_STOCK_ERROR"

export const GET_ALL_TOP_PRODUCTS_LOADING = "GET_ALL_TOP_PRODUCTS_LOADING"
export const GET_ALL_TOP_PRODUCTS_LOADED = "GET_ALL_TOP_PRODUCTS_LOADED"
export const GET_ALL_TOP_PRODUCTS_ERROR = "GET_ALL_TOP_PRODUCTS_ERROR"

export const GET_ALL_CUSTOMER_ACTIVITY_LOADING = "GET_ALL_CUSTOMER_ACTIVITY_LOADING"
export const GET_ALL_CUSTOMER_ACTIVITY_LOADED = "GET_ALL_CUSTOMER_ACTIVITY_LOADED"
export const GET_ALL_CUSTOMER_ACTIVITY_ERROR = "GET_ALL_CUSTOMER_ACTIVITY_ERROR"

export const GET_ALL_CUSTOMER_STATS_LOADING = "GET_ALL_CUSTOMER_STATS_LOADING"
export const GET_ALL_CUSTOMER_STATS_LOADED = "GET_ALL_CUSTOMER_STATS_LOADED"
export const GET_ALL_CUSTOMER_STATS_ERROR = "GET_ALL_CUSTOMER_STATS_ERROR"

export const GET_ALL_RECENT_ORDERS_LOADING = "GET_ALL_RECENT_ORDERS_LOADING"
export const GET_ALL_RECENT_ORDERS_LOADED = "GET_ALL_RECENT_ORDERS_LOADED"
export const GET_ALL_RECENT_ORDERS_ERROR = "GET_ALL_RECENT_ORDERS_ERROR"

export const GET_ALL_SALES_LOADING = "GET_ALL_SALES_LOADING"
export const GET_ALL_SALES_LOADED = "GET_ALL_SALES_LOADED"
export const GET_ALL_SALES_ERROR = "GET_ALL_SALES_ERROR"

export const GET_ALL_VISITORS_LOADING = "GET_ALL_VISITORS_LOADING"
export const GET_ALL_VISITORS_LOADED = "GET_ALL_VISITORS_LOADED"
export const GET_ALL_VISITORS_ERROR = "GET_ALL_VISITORS_ERROR"


export const GET_ALL_REAL_TIME_LOADING = "GET_ALL_REAL_TIME_LOADING"
export const GET_ALL_REAL_TIME_LOADED = "GET_ALL_REAL_TIME_LOADED"
export const GET_ALL_REAL_TIME_ERROR = "GET_ALL_REAL_TIME_ERROR"